#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1733800968

/*
 * Macros for device 'pixel_in_2_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIXEL_IN_2_PIO_'.
 * The prefix is the slave descriptor.
 */
#define PIXEL_IN_2_PIO_COMPONENT_TYPE altera_avalon_pio
#define PIXEL_IN_2_PIO_COMPONENT_NAME pixel_in_2_pio
#define PIXEL_IN_2_PIO_BASE 0x20000
#define PIXEL_IN_2_PIO_SPAN 16
#define PIXEL_IN_2_PIO_END 0x2000f
#define PIXEL_IN_2_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define PIXEL_IN_2_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIXEL_IN_2_PIO_CAPTURE 0
#define PIXEL_IN_2_PIO_DATA_WIDTH 8
#define PIXEL_IN_2_PIO_DO_TEST_BENCH_WIRING 0
#define PIXEL_IN_2_PIO_DRIVEN_SIM_VALUE 0
#define PIXEL_IN_2_PIO_EDGE_TYPE NONE
#define PIXEL_IN_2_PIO_FREQ 50000000
#define PIXEL_IN_2_PIO_HAS_IN 0
#define PIXEL_IN_2_PIO_HAS_OUT 1
#define PIXEL_IN_2_PIO_HAS_TRI 0
#define PIXEL_IN_2_PIO_IRQ_TYPE NONE
#define PIXEL_IN_2_PIO_RESET_VALUE 0

/*
 * Macros for device 'intr_capturer_0', class 'intr_capturer'
 * The macros are prefixed with 'INTR_CAPTURER_0_'.
 * The prefix is the slave descriptor.
 */
#define INTR_CAPTURER_0_COMPONENT_TYPE intr_capturer
#define INTR_CAPTURER_0_COMPONENT_NAME intr_capturer_0
#define INTR_CAPTURER_0_BASE 0x30000
#define INTR_CAPTURER_0_SPAN 8
#define INTR_CAPTURER_0_END 0x30007

/*
 * Macros for device 'pixel_out_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIXEL_OUT_PIO_'.
 * The prefix is the slave descriptor.
 */
#define PIXEL_OUT_PIO_COMPONENT_TYPE altera_avalon_pio
#define PIXEL_OUT_PIO_COMPONENT_NAME pixel_out_pio
#define PIXEL_OUT_PIO_BASE 0x40000
#define PIXEL_OUT_PIO_SPAN 16
#define PIXEL_OUT_PIO_END 0x4000f
#define PIXEL_OUT_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define PIXEL_OUT_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIXEL_OUT_PIO_CAPTURE 0
#define PIXEL_OUT_PIO_DATA_WIDTH 8
#define PIXEL_OUT_PIO_DO_TEST_BENCH_WIRING 0
#define PIXEL_OUT_PIO_DRIVEN_SIM_VALUE 0
#define PIXEL_OUT_PIO_EDGE_TYPE NONE
#define PIXEL_OUT_PIO_FREQ 50000000
#define PIXEL_OUT_PIO_HAS_IN 1
#define PIXEL_OUT_PIO_HAS_OUT 0
#define PIXEL_OUT_PIO_HAS_TRI 0
#define PIXEL_OUT_PIO_IRQ_TYPE NONE
#define PIXEL_OUT_PIO_RESET_VALUE 255

/*
 * Macros for device 'pixel_in_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIXEL_IN_PIO_'.
 * The prefix is the slave descriptor.
 */
#define PIXEL_IN_PIO_COMPONENT_TYPE altera_avalon_pio
#define PIXEL_IN_PIO_COMPONENT_NAME pixel_in_pio
#define PIXEL_IN_PIO_BASE 0x50000
#define PIXEL_IN_PIO_SPAN 16
#define PIXEL_IN_PIO_END 0x5000f
#define PIXEL_IN_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define PIXEL_IN_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIXEL_IN_PIO_CAPTURE 0
#define PIXEL_IN_PIO_DATA_WIDTH 8
#define PIXEL_IN_PIO_DO_TEST_BENCH_WIRING 0
#define PIXEL_IN_PIO_DRIVEN_SIM_VALUE 0
#define PIXEL_IN_PIO_EDGE_TYPE NONE
#define PIXEL_IN_PIO_FREQ 50000000
#define PIXEL_IN_PIO_HAS_IN 0
#define PIXEL_IN_PIO_HAS_OUT 1
#define PIXEL_IN_PIO_HAS_TRI 0
#define PIXEL_IN_PIO_IRQ_TYPE NONE
#define PIXEL_IN_PIO_RESET_VALUE 0

/*
 * Macros for device 'pixel_in_1_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIXEL_IN_1_PIO_'.
 * The prefix is the slave descriptor.
 */
#define PIXEL_IN_1_PIO_COMPONENT_TYPE altera_avalon_pio
#define PIXEL_IN_1_PIO_COMPONENT_NAME pixel_in_1_pio
#define PIXEL_IN_1_PIO_BASE 0x60000
#define PIXEL_IN_1_PIO_SPAN 16
#define PIXEL_IN_1_PIO_END 0x6000f
#define PIXEL_IN_1_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define PIXEL_IN_1_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIXEL_IN_1_PIO_CAPTURE 0
#define PIXEL_IN_1_PIO_DATA_WIDTH 8
#define PIXEL_IN_1_PIO_DO_TEST_BENCH_WIRING 0
#define PIXEL_IN_1_PIO_DRIVEN_SIM_VALUE 0
#define PIXEL_IN_1_PIO_EDGE_TYPE NONE
#define PIXEL_IN_1_PIO_FREQ 50000000
#define PIXEL_IN_1_PIO_HAS_IN 0
#define PIXEL_IN_1_PIO_HAS_OUT 1
#define PIXEL_IN_1_PIO_HAS_TRI 0
#define PIXEL_IN_1_PIO_IRQ_TYPE NONE
#define PIXEL_IN_1_PIO_RESET_VALUE 0


#endif /* _ALTERA_HPS_0_H_ */
